# Generated by Django 4.0.4 on 2022-05-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_student_student_user_courseenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courseitems', to='student.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='student.courseenrollment')),
            ],
        ),
    ]
